[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"

# HTML Minification
[[plugins]]
  package = "netlify-plugin-minify-html"

# CSS Minification
[[plugins]]
  package = "netlify-plugin-minify-css"

# JavaScript Minification
[[plugins]]
  package = "netlify-plugin-minify-js"

# Lighthouse Performance Monitoring
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Image Optimization
[[plugins]]
  package = "@netlify/plugin-image-optim"

[plugins.inputs]
  quality = 80
  format = "webp"
  width = 1920
  height = 1080

[plugins.inputs]
  minify = true
  bundle = true

[plugins.inputs]
  minify = true
  bundle = true
  mangle = true
  compress = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=*, geolocation=*"
    Content-Security-Policy = "default-src 'self' https: data: 'unsafe-inline' 'unsafe-eval'; img-src 'self' data: https:; media-src 'self' https:; connect-src 'self' https:;"
    Cache-Control = "public, max-age=31536000, immutable"
    Accept-Encoding = "gzip, br"
    Vary = "Accept-Encoding"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript"
    Brotli-Compression = "true"
    Gzip-Compression = "true"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css"
    Brotli-Compression = "true"
    Gzip-Compression = "true"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Brotli-Compression = "true"
    Gzip-Compression = "true"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "text/html; charset=utf-8"

[[headers]]
  for = "/*.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8" 